theme = "rose_pine"
# theme = "catppuccin_latte"
# theme = "autumn"
# theme = "tokyonight"
# theme = "catppuccin_macchiato"
# theme = "catppuccin_mocha"

[editor]
scrolloff = 8
line-number = "relative"
mouse = false
bufferline = "multiple" # Do I need this bufferline?
cursorline = true
true-color = true
# auto-save = true

[keys.normal]
G = ["goto_last_line"]

# Quick iteration on config changes..
C-o = ":config-open"
C-r = ":config-reload"

# Sane defaults..
esc = ["collapse_selection", "keep_primary_selection"]
C-u = [ "page_cursor_half_up", "align_view_center"]
C-d = [ "page_cursor_half_down","align_view_center"]

# LSP
K = ["hover"] # Vim lsp hover seems more convenient for now.

# Rust Related config
"," = { r = ":sh cargo run" } # Feature to have lang specific settings is not out yet...........

[keys.normal.g]
c = ["toggle_comments"] # vim`like commenting

[keys.select.g]
c = ["toggle_comments"] # vim`like commenting

[keys.normal.space]
G = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"] # Lazygit integration..
q = ":quit"

[keys.normal.space.c]
f = ":format"

[keys.insert]
C-space = ["completion"] # Toggle completion popup..

[editor.cursor-shape]
insert = "bar"

[editor.statusline]
left = ["separator", "version-control","separator", "file-name"]
# center = [  "separator" ]
right = ["spinner","separator" ,"diagnostics","separator" , "position", "position-percentage", "total-line-numbers" ]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-inlay-hints = true
display-messages = true

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.file-picker]
hidden = false # What does this do?
