theme = "rose_pine"
# theme = "catppuccin_latte"
# theme = "autumn"
# theme = "tokyonight"
# theme = "catppuccin_macchiato"
# theme = "catppuccin_mocha"

[editor]
scrolloff = 8
line-number = "relative"
mouse = false
bufferline = "multiple"
cursorline = true
true-color = true
# auto-save = true
# cursorcolumn = true # sniper-like feeling...

[keys.normal]
# Quick iteration on config changes
C-o = ":config-open"
C-r = ":config-reload"

esc = ["collapse_selection", "keep_primary_selection"]
C-u = [ "page_cursor_half_up", "align_view_center"]
C-d = [ "page_cursor_half_down","align_view_center"]

[keys.normal.space]
G = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
q = ":quit"

[editor.cursor-shape]
insert = "bar"

[editor.statusline]
left = ["separator", "version-control","separator", "file-name"]
# center = [  "separator" ]
right = ["spinner","separator" ,"diagnostics","separator" , "position", "position-percentage", "total-line-numbers" ]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-inlay-hints = true
display-messages = true

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.file-picker]
hidden = false # What does this do?


# ### https://docs.helix-editor.com/master/configuration.html#editorwhitespace-section
# [editor.whitespace.render]
# space = "all"
# tab = "all"
# newline = "none"
